/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "common_types.h"

#include <algorithm>



int _kResTypeValues[] = {
  ResType::Mapping,
  ResType::Configure,
  ResType::Strategy
};
const char* _kResTypeNames[] = {
  "Mapping",
  "Configure",
  "Strategy"
};
const std::map<int, const char*> _ResType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kResTypeValues, _kResTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


