/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef get_CONSTANTS_H
#define get_CONSTANTS_H

#include "get_types.h"



class getConstants {
 public:
  getConstants();

  int32_t WMESSAGE_V1_GET;
};

extern const getConstants g_get_constants;



#endif
