/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "get_constants.h"



const getConstants g_get_constants;

getConstants::getConstants() {
  WMESSAGE_V1_GET = 1025;

}



